#spring.security.user.name=meth
#spring.security.user.password=dummy

jwt.secret=dGhlU2VjcmV0
jwt.get.token.uri=/authenticate
jwt.refresh.token.uri=/refresh
jwt.http.request.header=Authorization
jwt.token.expiration.in.seconds=9000000


spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=kolhok
spring.data.mongodb.username=meth
spring.data.mongodb.password=dummy